-- CODE GO API - SETUP CREATURES DATABASE
-- Database name: codego (as configured in config.php)
-- Run this SQL file on your phpMyAdmin / MySQL server to create the creatures table and populate the initial data.

-- 1. Create table
CREATE TABLE IF NOT EXISTS `creatures` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `name_en` VARCHAR(100) NOT NULL,
  `scientific_name` VARCHAR(100) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `min_depth` INT NOT NULL,
  `max_depth` INT NOT NULL,
  `danger_level` INT NOT NULL,
  `size_human_ratio` TEXT NOT NULL,
  `size_human_ratio_en` TEXT NOT NULL,
  `human_size_meters` DOUBLE NOT NULL,
  `creature_size_meters` DOUBLE NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `ambient_sound` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `description_en` TEXT NOT NULL,
  `is_locked` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Clean table before insert (optional, to avoid duplicate keys)
TRUNCATE TABLE `creatures`;

-- 3. Insert initial 15 creatures with remote server URLs
INSERT INTO `creatures` (
  `id`, `name`, `name_en`, `scientific_name`, `type`, `min_depth`, `max_depth`, 
  `danger_level`, `size_human_ratio`, `size_human_ratio_en`, `human_size_meters`, 
  `creature_size_meters`, `image_url`, `ambient_sound`, `description`, `description_en`, `is_locked`
) VALUES 
('clownfish', 
 'Cá Hề & Rạn San Hô', 
 'Clownfish & Coral Reef', 
 'Amphiprioninae', 
 'real', 
 0, 
 50, 
 1, 
 'Rất nhỏ (Khoảng 10-15 cm, nhỏ hơn bàn tay người)', 
 'Very small (About 10-15 cm, smaller than a human hand)', 
 1.8, 
 0.15, 
 'https://codego.io.vn/api/uploads/creatures/clownfish.png', 
 'https://codego.io.vn/api/uploads/sounds/shallow_water.mp3', 
 'Ở vùng nước nông ngập tràn ánh nắng mặt trời, các rạn san hô rực rỡ sắc màu là nhà của loài cá hề nhỏ bé. Thói quen của chúng là ẩn náu trong các tua độc của hải quỳ để tránh kẻ săn mồi, thức ăn ưa thích là sinh vật phù du và giáp xác nhỏ trôi nổi. Đối thủ - đối trọng cận nước của chúng là các loài cá mú nhỏ hoặc cá bướm luôn sẵn sàng tranh giành rạn san hô sinh sống làm lãnh địa riêng.', 
 'In the sun-drenched shallow waters, vibrant coral reefs are home to the tiny clownfish. They hide within the venomous tentacles of sea anemones to evade predators, feeding primarily on drifting plankton and tiny crustaceans. Their immediate rivals on the reef are small groupers or butterflyfish, constantly competing for reef territory.', 
 0),

('great_white_shark', 
 'Cá Mập Trắng Lớn', 
 'Great White Shark', 
 'Carcharodon carcharias', 
 'real', 
 20, 
 1200, 
 4, 
 'Lớn gấp 3 lần con người (Dài từ 4.5m - 6m)', 
 '3 times larger than a human (4.5m - 6m long)', 
 1.8, 
 6.0, 
 'https://codego.io.vn/api/uploads/creatures/great_white_shark.png', 
 'https://codego.io.vn/api/uploads/sounds/shark_heartbeat.mp3', 
 'Kẻ săn mồi đỉnh cao cận mặt nước sở hữu bộ hàm chứa hàng trăm chiếc răng cưa sắc nhọn và khả năng đánh hơi một giọt máu cách xa hàng km. Thói quen săn mồi của nó là phục kích từ dưới vực sâu lao vọt lên tấn công chớp nhoáng xé xác con mồi, thức ăn ưa thích là hải cẩu và sư tử biển giàu mỡ. Đối thủ - đối trọng lớn nhất của Cá Mập Trắng chính là Cá Voi Sát Thủ (Orca), loài động vật thông minh và tàn nhẫn duy nhất có thể săn lùng và đánh bại nó.', 
 'The apex predator of the upper waters possesses jaws lined with hundreds of serrated teeth and can scent a single drop of blood miles away. It hunts by launching ambush attacks from below to tear prey apart, feeding on fat-rich seals and sea lions. The Great White\'s greatest adversary is the Orca, the only intelligent mammal capable of hunting and defeating it.', 
 0),

('oarfish', 
 'Cá Hố Hoàng Đế (Oarfish)', 
 'Giant Oarfish', 
 'Regalecus glesne', 
 'real', 
 200, 
 1000, 
 2, 
 'Dài gấp 5 lần chiều cao con người (Dài tới 8m - 11m)', 
 '5 times longer than human height (8m - 11m long)', 
 1.8, 
 9.0, 
 'https://codego.io.vn/api/uploads/creatures/oarfish.png', 
 '', 
 'Thân hình dài ngoằn ngoèo tựa như rồng biển khổng lồ, loài cá xương dài nhất thế giới này mang theo điềm báo động đất cận kề từ lòng biển thẳm. Nó di chuyển thẳng đứng trong vùng nửa tối bằng cách uốn lượn vây lưng mỏng manh để lơ lửng ngụy trang, thức ăn ưa thích là loài nhuyễn thể và giáp xác nhỏ trôi nổi tự do. Đối thủ - đối trọng trong chuỗi thức ăn của nó là Cá Mập Đại Dương khổng lồ chuyên tấn công cắn rỉa và săn đuổi những cơ thể dài ngoằn ngoèo dễ bị phát hiện này.', 
 'With a long, ribbon-like body resembling a giant sea dragon, the world\'s longest bony fish is said to bring warnings of earthquakes from the deep ocean floor. It floats vertically in the twilight zone, rippling its dorsal fin to hover in camouflage, feeding on krill and tiny free-floating crustaceans. Its main rival in the food chain is the oceanic shark, which attacks and bites these long, easily spotted bodies.', 
 0),

('giant_squid', 
 'Mực Khổng Lồ', 
 'Giant Squid', 
 'Architeuthis dux', 
 'real', 
 300, 
 1000, 
 4, 
 'Dài gấp 7-8 lần con người (Dài tới 12m - 14m)', 
 '7-8 times longer than a human (12m - 14m long)', 
 1.8, 
 13.0, 
 'https://codego.io.vn/api/uploads/creatures/giant_squid.png', 
 '', 
 'Huyền thoại bóng đêm đại dương sở hữu đôi mắt to bằng chiếc đĩa ăn để nhìn trong bóng tối và các xúc tu cực dài trang bị vòng giác hút răng cưa sắc bén. Thói quen săn mồi của nó là âm thầm rình rập rồi phóng xúc tu chộp bắt nhanh như chớp từ bóng tối sâu thẳm, thức ăn ưa thích là các loài cá tầng sâu và các mực khác nhỏ hơn. Đối thủ - đối trọng truyền kiếp của Mực Khổng Lồ chính là Cá Voi Nhà Táng, những cuộc chiến sinh tử giữa chúng thường để lại các vết sẹo giác hút chằng chit trên da cá voi.', 
 'A legend of the deep ocean darkness, it possesses dinner plate-sized eyes to see in pitch black and long feeding tentacles armed with sharp, serrated suckers. It stalks its prey in silence before striking with lightning speed from the shadows, feeding on deep-sea fish and smaller squid. Its eternal arch-nemesis is the Sperm Whale; their deadly battles leave tangled scars of suckers on the whale\'s skin.', 
 0),

('vampire_squid', 
 'Mực Ma Cà Rồng', 
 'Vampire Squid', 
 'Vampyroteuthis infernalis', 
 'real', 
 600, 
 900, 
 2, 
 'Nhỏ hơn con người (Dài khoảng 30 cm)', 
 'Smaller than a human (About 30 cm long)', 
 1.8, 
 0.3, 
 'https://codego.io.vn/api/uploads/creatures/vampire_squid.png', 
 '', 
 'Sinh vật mang tên \'Mực ma cà rồng từ địa ngục\' sở hữu lớp màng đen như cánh dơi bao phủ cơ thể màu đỏ sẫm ma quái đầy gai nhọn. Sống ở vùng nước thiếu oxy cực hạn, thói quen của nó là thu mình lại ngụy trang thành một quả bóng gai, thức ăn ưa thích là \'tuyết đại dương\' (các mảnh xác hữu cơ rơi rụng chìm xuống đáy). Đối thủ - đối trọng lớn nhất của nó là các loài cá săn mồi tầng sâu mắt to như Cá Rắn biển, buộc nó phải thích nghi bằng xúc tu phát quang xanh lá đánh lạc hướng đối thủ.', 
 'Named the \'vampire squid from hell,\' it possesses a bat-like black webbing lined with sharp spines over its dark red body. Living in oxygen-minimum zones, it curls into a spiny ball for defense, feeding on \'marine snow\' (organic detritus sinking from above). Its biggest threats are large-eyed deep-sea predators like dragonfish, which it evades using bioluminescent tips on its tentacles.', 
 0),

('anglerfish', 
 'Cá Vây Chân (Anglerfish)', 
 'Anglerfish', 
 'Melanocetus johnsonii', 
 'real', 
 1000, 
 4000, 
 3, 
 'Nhỏ hơn con người (Khoảng 20-30 cm, nhưng hàm răng cực lớn)', 
 'Smaller than a human (About 20-30 cm, but with a massive jaw)', 
 1.8, 
 0.25, 
 'https://codego.io.vn/api/uploads/creatures/anglerfish.png', 
 'https://codego.io.vn/api/uploads/sounds/angler_breath.mp3', 
 'Gương mặt đại diện cho ác mộng biển sâu với hàm răng nhọn hoắt đan cài dày đặc và cơ thể đen kịt biến dạng dưới áp lực hàng trăm atmosphere. Thói quen săn mồi của con cái là nằm bất động tuyệt đối, dùng chiếc râu phát sinh học sáng rực dụ dỗ con mồi bơi thẳng vào chiếc miệng khổng lồ, thức ăn ưa thích là bất kỳ sinh vật nào đi lạc vừa kích thước. Đối thủ - đối trọng trực tiếp của nó là Cá Rồng Đen, loài cá phát quang sở hữu hàm răng dài ngụy trang tinh ranh cùng phân khúc độ sâu thẳm.', 
 'The face of deep-sea nightmares, featuring needle-like teeth and a body deformed by hundreds of atmospheres of pressure. The female hunts by remaining completely motionless, using a glowing bioluminescent lure to draw prey directly into its massive mouth, feeding on any lost creature. Its direct rival is the Black Dragonfish, another toothy bioluminescent predator patrolling the same abyssal depths.', 
 0),

('giant_isopod', 
 'Bọ Chân Đều Khổng Lồ', 
 'Giant Isopod', 
 'Bathynomus giganteus', 
 'real', 
 170, 
 2140, 
 2, 
 'Kích thước bằng một cánh tay người (Dài khoảng 30-50 cm)', 
 'About the size of a human arm (30-50 cm long)', 
 1.8, 
 0.45, 
 'https://codego.io.vn/api/uploads/creatures/giant_isopod.png', 
 'https://codego.io.vn/api/uploads/sounds/The_BLOOP.mp3', 
 'Trông như một con bọ cánh cứng khổng lồ thời tiền sử bò sát đáy biển, bảo vệ bởi lớp giáp dày cứng chịu được sức ép nước đè nặng cực lớn. Chúng là loài ăn xác thối vô cùng kiên nhẫn, thức ăn ưa thích là xác cá voi chết chình (xác chìm đại dương) rơi rụng từ tầng nước ấm phía trên. Đối thủ - đối trọng cạnh tranh nguồn dinh dưỡng hiếm hoi đáy vực của chúng là loài Cá Chình Myxin (Hagfish) chuyên tiết chất nhầy bao phủ ngăn cản đối thủ ăn mồi.', 
 'Looking like a prehistoric giant beetle crawling on the seabed, it is armored with a thick exoskeleton to withstand crushing pressures. It is an extremely patient scavenger, feeding on sunken whale carcasses (whale falls) that drift down from upper waters. Its chief competitor for these scarce abyssal nutrients is the slime-producing Hagfish.', 
 0),

('black_dragonfish', 
 'Cá Rồng Đen (Black Dragonfish)', 
 'Black Dragonfish', 
 'Idiacanthus atlanticus', 
 'real', 
 1500, 
 3000, 
 3, 
 'Nhỏ hơn con người (Dài khoảng 40 cm)', 
 'Smaller than a human (About 40 cm long)', 
 1.8, 
 0.4, 
 'https://codego.io.vn/api/uploads/creatures/black_dragonfish.png', 
 'https://codego.io.vn/api/uploads/sounds/The_BLOOP.mp3', 
 'Loài cá rồng sở hữu làn da đen tuyền hấp thụ hoàn toàn ánh sáng và hàm răng dài sắc nhọn đến mức không thể khép khít miệng lại được. Thói quen săn mồi của nó là nhấp nháy phát quang cơ quan dọ thân để thôi miên con mồi rồi tung đòn táp bất ngờ từ bóng đêm, thức ăn ưa thích là các loài cá con và giáp xác nhỏ phát sáng. Đối thủ - đối trọng sinh tồn cận kề của Cá Rồng Đen chính là Cá Vây Chân, cuộc cạnh tranh thức ăn vô cùng khốc liệt trong bóng tối vĩnh hằng.', 
 'A deep-sea dragon with pitch-black skin that absorbs all light and teeth so long it cannot close its mouth. It hunts by flashing photophores along its body to hypnotize prey before striking from the dark, feeding on small fish and bioluminescent crustaceans. Its chief rival is the Anglerfish, locked in a fierce battle for survival in the eternal night.', 
 0),

('greenland_shark', 
 'Cá Mập Greenland', 
 'Greenland Shark', 
 'Somniosus microcephalus', 
 'real', 
 1800, 
 2200, 
 3, 
 'To gấp 3-4 lần con người (Dài từ 5m - 7m)', 
 '3-4 times larger than a human (5m - 7m long)', 
 1.8, 
 6.5, 
 'https://codego.io.vn/api/uploads/creatures/greenland_shark.png', 
 '', 
 'Loài động vật có xương sống thọ nhất hành tinh di chuyển vô cùng chậm rãi dưới làn nước băng giá tăm tối cận cực bắc sâu thẳm. Thói quen săn mồi của nó là âm thầm áp sát tấn công những con hải cẩu đang ngủ dưới băng, thức ăn ưa thích là các loại cá tuyết và xác thối động vật chìm sâu. Đối thủ - đối trọng đáng gờm nhất của nó ở tầng mặt nước là loài Cá Voi Sát Thủ Bắc Cực, ép buộc nó phải chọn cách thích nghi sinh sống hoàn toàn dưới tầng nước lạnh buốt sâu thẳm.', 
 'The longest-lived vertebrate on Earth crawls slowly through freezing, dark waters near the polar depths. It hunts sleeping seals under the ice and scavenges sunken carcasses, moving at a glacial pace. Its greatest threat at the surface is the Arctic Orca, forcing it to live its entire life in the deep polar abyss.', 
 0),

('kraken', 
 'Thủy Quái Kraken', 
 'The Kraken', 
 'Architeuthis Gigantus (Myth)', 
 'myth', 
 2000, 
 5000, 
 5, 
 'Khổng lồ (Dài hơn 60m, lớn hơn tàu chiến)', 
 'Colossal (Over 60m, larger than a warship)', 
 1.8, 
 60.0, 
 'https://codego.io.vn/api/uploads/creatures/kraken.png', 
 'https://codego.io.vn/api/uploads/sounds/kraken_roar.mp3', 
 'Thủy quái mực khổng lồ huyền thoại vùng biển Bắc Âu chuyên kéo chìm các chiến thuyền gỗ lớn xuống đáy biển sâu bằng những xúc tu siết nghẹt cứng. Thói quen săn mồi của nó là tạo ra những cơn xoáy nước khổng lồ hút chìm mọi vật thể nổi trên biển rồi nuốt chửng, thức ăn ưa thích là các loài cá khổng lồ và cá voi sừng. Đối thủ - đối trọng ngang tài ngang sức thống trị lòng đại dương của Kraken chính là Mãng Xà Biển (Sea Serpent) khổng lồ luôn canh giữ các rặng núi nứt sâu.', 
 'A legendary giant squid of Norse mythology that drags large wooden warships down to the ocean floor with its crushing tentacles. It hunts by creating massive whirlpools to pull floating vessels down, feeding on giant fish and whales. Its ocean-ruling rival is the legendary Sea Serpent, which guards the deep tectonic rifts.', 
 1),

('the_bloop', 
 'Nguồn phát âm thanh \'The Bloop\'', 
 'The Bloop Sound Source', 
 'Unknown Organic Source', 
 'myth', 
 4000, 
 7000, 
 4, 
 'Lớn hơn cả Cá Voi Xanh (Ước tính dài 215m)', 
 'Larger than a Blue Whale (Estimated 215m long)', 
 1.8, 
 215.0, 
 'https://codego.io.vn/api/uploads/creatures/the_bloop.png', 
 'https://codego.io.vn/api/uploads/sounds/The_BLOOP.mp3', 
 'Thực thể sinh học khổng lồ vô danh ẩn mình phát ra sóng âm tần số siêu thấp lan rộng khắp Thái Bình Dương rộng lớn hàng ngàn cây số. Thói quen săn mồi của siêu quái vật này là nuốt chửng toàn bộ các đàn cá mập bằng chiếc miệng khổng lồ như hang động, thức ăn ưa thích là các loài cá voi xanh lớn nhất và mực khổng lồ. Đối thủ - đối trọng duy nhất tương xứng với tầm vóc khổng lồ phi thực tế của nó dưới lòng đại dương sâu thẳm chính là Đại Long Leviathan đang ngủ say đáy thẳm.', 
 'An unnamed colossal organic entity that emits ultra-low-frequency sound waves sweeping across thousands of miles of the Pacific. This super-predator consumes entire schools of sharks in its cavernous mouth, feeding on blue whales and giant squids. Its only rival in size and power is the sleeping Great Leviathan.', 
 0),

('leviathan', 
 'Đại Long Leviathan', 
 'Great Leviathan', 
 'Cetus Diabolicus (Myth)', 
 'myth', 
 6000, 
 11000, 
 5, 
 'Vô hạn (Dài hàng trăm mét đến hàng km)', 
 'Infinite (Hundreds of meters to kilometers long)', 
 1.8, 
 350.0, 
 'https://codego.io.vn/api/uploads/creatures/leviathan.png', 
 'https://codego.io.vn/api/uploads/sounds/leviathan_groan.mp3', 
 'Vua rồng biển thần thoại bọc lớp vảy giáp gai cứng hơn thép dòng chảy hơi thở sục sôi nước thẳm và đôi mắt sáng rực rỡ xua tan bóng đêm tăm tối. Thói quen săn mồi của nó là càn quét đáy biển tạo nên những cơn chấn động thảm họa núi lửa, thức ăn ưa thích là các thực thể cổ đại ngủ sâu đại dương. Đối thủ - đối trọng vĩnh cửu tranh giành chủ quyền tuyệt đối của Leviathan tại các rãnh vực thẳm sâu nhất không ai khác chính là Tà Thần Cthulhu.', 
 'A mythical dragon king of the sea covered in scales harder than steel, breathing boiling abyssal steam, with eyes that pierce the eternal dark. It hunts by sweeping across the seabed, triggering catastrophic earthquakes and volcanic eruptions. Its eternal rival for absolute dominion over the deep trenches is Cthulhu.', 
 1),

('sea_serpent', 
 'Mãng Xà Biển', 
 'Sea Serpent', 
 'Serpens Oceanus (Myth)', 
 'myth', 
 1000, 
 6000, 
 4, 
 'Cực dài (Dài từ 80m - 120m, uốn lượn như dãy núi)', 
 'Extremely long (80m - 120m long)', 
 1.8, 
 100.0, 
 'https://codego.io.vn/api/uploads/creatures/Sea_serpent_coiling.png', 
 'https://codego.io.vn/api/uploads/sounds/sea_serpent.mp3', 
 'Ác mộng của những nhà hàng hải cổ đại, sinh vật dạng bò sát khổng lồ dài hơn trăm mét uốn lượn trong lòng biển sâu. Sống ẩn mình giữa các vực thẳm từ 1000m đến 6000m, thói quen săn mồi của nó là ngụy trang như một rặng núi đá đen rồi bất ngờ lao ra quấn siết con mồi đến nát vụn xương cốt trước khi nuốt chửng. Thức ăn ưa thích của Mãng Xà Biển là Mực Khổng Lồ và các loài cá voi đi lạc xuống tầng sâu. Đối thủ - đối trọng truyền kiếp của nó chính là Thủy Quái Kraken. Mỗi khi hai sinh vật huyền thoại này đụng độ, những vòng quấn nghẹt thở và những xúc tu đầy gai nhọn của chúng tạo ra những cơn chấn động và dòng hải lưu ngầm dữ dội làm chao đảo thềm lục địa.', 
 'The dread of ancient sailors, a massive reptilian creature stretching over a hundred meters. Living in abysses between 1,000m and 6,000m, it camouflages as a black ridge before constricting its prey. It feeds on giant squids and lost whales. Its eternal nemesis is the Kraken; their deadly battles leave tangled scars of suckers on the whale\'s skin.', 
 0),

('cthulhu', 
 'Tà Thần Cthulhu', 
 'Cthulhu', 
 'Great Old One (Myth)', 
 'myth', 
 8000, 
 11000, 
 5, 
 'Kẻ thống trị vũ trụ (Cao hơn 300m, sải cánh khổng lồ)', 
 'Cosmic Ruler (Over 300m tall, with massive wings)', 
 1.8, 
 320.0, 
 'https://codego.io.vn/api/uploads/creatures/Cthulhu.png', 
 'https://codego.io.vn/api/uploads/sounds/Cthulhu.mp3', 
 'Thực thể vũ trụ tà ác đang ngủ say tại thành phố chìm sâu R\'lyeh ở nơi tận cùng của thế giới. Thói quen săn mồi của Cthulhu không giống bất kỳ loài sinh vật trần tục nào: nó săn lùng lý trí và linh hồn của con người bằng cách phát ra các bước sóng thần giao cách cảm điên loạn xuyên qua làn nước đại dương sâu thẳm. Thức ăn ưa thích của nó là nỗi sợ hãi tột cùng và sự cuồng tín của những thủy thủ hoặc nhà thám hiểm đi lạc. Đối thủ - đối trọng lớn nhất của Cthulhu tại rãnh sâu Mariana chính là Đại Long Leviathan - vị vua thống trị tuyệt đối của rãnh đại dương này. Cuộc đối đầu giữa trí tuệ tà ác ngoài vũ trụ và thực thể hỗn mang cổ đại hứa hẹn sẽ xé toạc ranh giới thực tại.', 
 'A malevolent cosmic entity sleeping in the sunken city of R\'lyeh at the edge of the world. It hunts human sanity by projecting maddening telepathic waves through the deep ocean. It feeds on the terror of lost explorers. Its greatest rival in the Mariana Trench is the Great Leviathan, the absolute ruler of the deep abyss.', 
 1),

('megalodon', 
 'Siêu Cá Mập Megalodon', 
 'Megalodon', 
 'Otodus megalodon', 
 'myth', 
 50, 
 1500, 
 5, 
 'Khổng lồ (Dài từ 15m - 20m, răng to bằng bàn tay)', 
 'Gigantic (15m - 20m long, teeth size of a hand)', 
 1.8, 
 18.0, 
 'https://codego.io.vn/api/uploads/creatures/megalodon.png', 
 '', 
 'Vua săn mồi đại dương thời tiền sử đã được tái hiện trong nhiều bộ phim và trò chơi điện tử nổi tiếng. Thói quen săn mồi của nó là lao vọt từ dưới đáy sâu với tốc độ kinh hoàng rồi dùng cú táp nghiền nát xương với lực cắn lên tới 18 tấn làm tê liệt mục tiêu. Thức ăn ưa thích của Megalodon là các loài cá voi tấm sừng lớn và rùa biển cổ đại. Đối thủ - đối trọng ngang sức duy nhất của nó chính là siêu quái vật Leviathan hoặc cá voi ăn thịt khổng lồ Livyatan melvillei tranh giành ngôi vương thống trị biển cả.', 
 'The prehistoric super-shark featured in popular films and video games. It hunts by rushing from the deep at terrifying speeds, striking with an 18-ton bite force to crush whale bones. It feeds on baleen whales and giant turtles. Its only rival is the Leviathan or the predatory Livyatan melvillei.', 
 0),

('reaper_leviathan', 
 'Thủy Quái Reaper Leviathan', 
 'Reaper Leviathan', 
 'Levia Reapus (Myth)', 
 'myth', 
 100, 
 500, 
 5, 
 'Cực kỳ khổng lồ (Dài 55m, gấp 30 lần con người)', 
 'Colossal (55m long, 30 times larger than a human)', 
 1.8, 
 55.0, 
 'https://codego.io.vn/api/uploads/creatures/reaper_leviathan.png', 
 'https://codego.io.vn/api/uploads/sounds/reaper_leviathan.mp3', 
 'Cơn ác mộng kinh hoàng trong các trò chơi và bộ phim viễn tưởng về thám hiểm đại dương với tiếng gầm rú kinh tởm vang vọng từ khoảng cách xa. Sống tại các vùng nước nửa tối, thói quen săn mồi của nó là lén lút áp sát từ phía sau, dùng bốn chiếc sừng đỏ kẹp chặt rồi nuốt chửng cả thợ lặn lẫn tàu ngầm nhỏ. Thức ăn ưa thích của Reaper là bất kỳ sinh vật hoặc phương tiện nào đi lạc vào lãnh địa tuần tra của nó. Đối thủ - đối trọng nguy hiểm của nó chính là sinh vật giáp sắt cua biển khổng lồ hoặc Ghost Leviathan thống trị vùng nước sâu hơn.', 
 'A terrifying nightmare from sci-fi ocean exploration games and movies, whose ghastly roar echoes across vast distances. It stalks from behind in the twilight zone, pinning vessels with four red claws before consuming them. It feeds on anything entering its territory, and clashes with Ghost Leviathans.', 
 0),

('jormungandr', 
 'Mãng Xà Thế Giới Jörmungandr', 
 'World Serpent Jörmungandr', 
 'Midgard Serpent (Myth)', 
 'myth', 
 4000, 
 10000, 
 5, 
 'Không tưởng (Dài hàng chục km, quấn quanh Trái Đất)', 
 'Midgard Serpent (Kilometers long, wraps around the Earth)', 
 1.8, 
 400.0, 
 'https://codego.io.vn/api/uploads/creatures/jormungandr.png', 
 'https://codego.io.vn/api/uploads/sounds/lagiacrus.mp3', 
 'Mãng Xà Thế Giới khổng lồ trong thần thoại Bắc Âu cổ đại sở hữu kích thước khổng lồ quấn quanh Midgard — nguồn cảm hứng bất tận cho vô số bộ phim và trò chơi điện tử trên toàn thế giới. Thói quen của nó là nằm bất động cuộn quanh đáy biển sâu kiến tạo thềm địa chất, hơi thở của nó có thể phun độc cực mạnh ăn mòn vạn vật. Thức ăn ưa thích của nó là các loài quái vật biển khổng lồ cổ đại dưới rãnh sâu. Đối thủ - đối trọng định mệnh của Jörmungandr chính là thần sấm Thor, cuộc chiến cuối cùng giữa họ trong sự kiện Ragnarok được dự báo sẽ hủy diệt cả thế giới.', 
 'The Midgard Serpent from Norse mythology, wrapping around the entire world and inspiring countless games and films. It lies coiled at the bottom of the deep ocean, emitting toxic vapors that corrode all metals. It feeds on abyssal monsters. Its destined rival is Thor; their final battle during Ragnarok will destroy the world.', 
 0),

('lagiacrus', 
 'Lôi Hải Long Lagiacrus', 
 'Lord of the Seas Lagiacrus', 
 'Hải Long Sấm (Myth)', 
 'myth', 
 150, 
 1200, 
 4, 
 'Cực lớn (Dài khoảng 30m, to gấp 15 lần thợ lặn)', 
 'Massive (About 30m long)', 
 1.8, 
 30.0, 
 'https://codego.io.vn/api/uploads/creatures/lagiacrus.png', 
 'https://codego.io.vn/api/uploads/sounds/lagiacrus.mp3', 
 'Chúa tể biển cả Lôi Hải Long huyền thoại sở hữu lớp vảy màu xanh đại dương phát điện cực mạnh — một trong những sinh vật truyền thuyết được yêu thích trong nhiều trò chơi và bộ phim viễn tưởng. Thói quen săn mồi của nó là tích tụ luồng điện cao thế phóng ra làm tê liệt cả một vùng biển lớn quanh mục tiêu trước khi xông tới cắn xé. Thức ăn ưa thích của Lagiacrus là đàn cá mập đại dương và các loài giáp xác khổng lồ dưới rạn san hô sâu. Đối thủ - đối trọng truyền kiếp của nó chính là rồng lửa thống trị bầu trời hoặc các thợ săn rồng huyền thoại luôn muốn đoạt lấy chiếc sừng sấm sét của nó.', 
 'The legendary Lord of the Seas clad in ocean-blue scales capable of releasing high-voltage electrical discharges. It hunts by discharging electricity to paralyze marine life in a large area before striking. It feeds on ocean sharks and giant crustaceans. Its rivals are dragons of the skies and legendary hunters.', 
 0),

('ghost_leviathan', 
 'Thủy Quái Ghost Leviathan', 
 'Ghost Leviathan', 
 'Phù Du Vực Thẳm (Myth)', 
 'myth', 
 1200, 
 8000, 
 5, 
 'Khổng lồ phát quang (Dài 107m, cơ thể trong suốt)', 
 'Bioluminescent giant (107m long, translucent body)', 
 1.8, 
 107.0, 
 'https://codego.io.vn/api/uploads/creatures/ghost_leviathan.png', 
 'https://codego.io.vn/api/uploads/sounds/leviathan_groan.mp3', 
 'Siêu thực thể phát quang trong suốt huyền bí từ các truyền thuyết và thế giới viễn tưởng, cư ngụ tại các vùng ranh giới hư vô tăm tối của đáy đại dương sâu thẳm. Thói quen săn mồi của nó là tuần tra ranh giới lãnh thổ một cách giận dữ, bất ngờ phóng ra tấn công trực diện từ bóng tối bằng cái đầu búa cứng cáp khi phát hiện rung động. Thức ăn ưa thích của nó là các loài giáp xác nhỏ phát sáng sinh sống quanh miệng núi lửa ngầm sâu thẳm. Đối thủ - đối trọng tự nhiên lớn nhất của nó chính là Reaper Leviathan tranh giành các vùng nước giao thoa hoặc giáp sắt cua ngầm Sea Dragon.', 
 'A majestic, bioluminescent translucent entity from deep-sea legends, dwelling at the edge of the void. It aggressively patrols its territory, launching head-on rams with its hammer-shaped head when detecting vibrations. It feeds on microscopic organisms and clashes with Reaper Leviathans.', 
 0),

('godzilla', 
 'Vua Quái Thú Godzillaa', 
 'King of the Monsters Godzillaa', 
 'Titanus Godzillaa (Myth)', 
 'myth', 
 1000, 
 9000, 
 5, 
 'Siêu khổng lồ (Cao 108m, nặng 90,000 tấn)', 
 'Titanus (108m tall, 90,000 tons)', 
 1.8, 
 108.0, 
 'https://codego.io.vn/api/uploads/creatures/Godzilla_2014.png', 
 'https://codego.io.vn/api/uploads/sounds/Godzilla.mp3', 
 'Vua của các loài quái thú khổng lồ (Alpha Titan) thường ngủ say tại các vực thẳm kiến tạo sâu thẳm dưới đáy Thái Bình Dương — nguồn cảm hứng cho vô số bộ phim và trò chơi điện tử đình đám trên toàn thế giới. Thói quen của Godzillaa là hấp thụ phóng xạ hạt nhân từ lõi Trái Đất để nạp năng lượng, khi thức tỉnh nó săn lùng các Titan cổ đại phá hoại sự cân bằng tự nhiên và phóng ra luồng hơi thở nguyên tử hủy diệt vạn vật. Đối thủ - đối trọng truyền kiếp lớn nhất của Godzillaa chính là rồng ba đầu ngoài vũ trụ hoặc các loài quái thú ký sinh tranh giành ngai vàng Alpha Titan thống trị Trái Đất.', 
 'The Alpha Titan king of monsters who sleeps in tectonic trenches under the Pacific, featured in blockbuster films. It absorbs nuclear radiation from the Earth\'s core to recharge, awakening to fight Titans that threaten the natural balance. Its archenemy is the three-headed space dragon or parasitic MUTOs.', 
 1);
